/**
 * Curated related-tool links for high-traffic and tightly related pages.
 * Falls back to same-category tools when a slug has no curated list.
 */
export const relatedToolSlugs: Record<string, string[]> = {
  "roi-calculator": [
    "budget-calculator",
    "buying-power-calculator",
    "sales-tax-calculator",
    "compound-interest-calculator",
    "break-even-calculator",
    "percentage-calculator",
  ],
  "down-payment-calculator": [
    "buying-power-calculator",
    "mortgage-calculator",
    "loan-calculator",
    "amortization-schedule",
    "refinance-calculator",
    "budget-calculator",
  ],
  "code-comparison": [
    "text-diff",
    "json-formatter",
    "json-generator",
    "regex-tester",
    "markdown-editor",
    "hash-generator",
  ],
  "png-to-webp": [
    "image-compressor",
    "image-cropper",
    "image-converter",
    "png-to-jpg",
    "webp-to-png",
    "image-resizer",
  ],
  "aspect-ratio-finder": [
    "image-cropper",
    "image-resizer",
    "image-compressor",
    "image-converter",
    "favicon-generator",
    "png-to-webp",
  ],
  "buying-power-calculator": [
    "inflation-calculator",
    "roi-calculator",
    "budget-calculator",
    "down-payment-calculator",
    "salary-hourly-converter",
    "currency-converter",
  ],
  "budget-calculator": [
    "roi-calculator",
    "emergency-fund-calculator",
    "sales-tax-calculator",
    "tip-calculator",
    "salary-hourly-converter",
    "net-worth-calculator",
  ],
  "sales-tax-calculator": [
    "budget-calculator",
    "tip-calculator",
    "discount-markup-calculator",
    "percentage-calculator",
    "roi-calculator",
    "income-tax-estimator",
  ],
  "random-number-generator": [
    "name-picker",
    "list-shuffler",
    "team-splitter",
    "dice-roller",
    "coin-flip",
    "yes-no-picker",
  ],
  "team-splitter": [
    "name-picker",
    "list-shuffler",
    "random-number-generator",
    "dice-roller",
    "coin-flip",
    "yes-no-picker",
  ],
  "emergency-fund-calculator": [
    "budget-calculator",
    "net-worth-calculator",
    "retirement-calculator",
    "debt-payoff-calculator",
    "salary-hourly-converter",
    "compound-interest-calculator",
  ],
  "image-compressor": [
    "png-to-webp",
    "image-resizer",
    "image-cropper",
    "image-converter",
    "jpg-to-png",
    "png-to-jpg",
  ],
  "image-cropper": [
    "aspect-ratio-finder",
    "image-resizer",
    "image-compressor",
    "png-to-webp",
    "background-remover",
    "favicon-generator",
  ],
  "mortgage-calculator": [
    "down-payment-calculator",
    "amortization-schedule",
    "refinance-calculator",
    "loan-calculator",
    "buying-power-calculator",
    "budget-calculator",
  ],
  "json-generator": [
    "json-formatter",
    "code-comparison",
    "regex-tester",
    "uuid-generator",
    "base64-encoder",
    "hash-generator",
  ],
  "text-diff": [
    "code-comparison",
    "word-counter",
    "case-converter",
    "remove-duplicates",
    "markdown-editor",
    "json-formatter",
  ],
};
