
/**
 * Curated related-tool links for high-traffic and tightly related pages.
 * Falls back to same-category tools when a slug has no curated list.
 */
export const relatedToolSlugs: Record<string, string[]> = {
  "spin-the-wheel": ["name-picker", "random-number-generator", "coin-flip"],
  "days-from-today": ["days-between-dates", "age-calculator", "date-calculator"],
  "profit-margin-calculator": ["discount-markup-calculator", "roi-calculator", "break-even-calculator"],
  "ratio-proportion-calculator": ["percentage-calculator", "fraction-calculator", "unit-converter"],
  "lcm-calculator": ["gcf-calculator", "prime-factor-calculator", "fraction-calculator"],
  "gcf-calculator": ["lcm-calculator", "prime-factor-calculator", "fraction-calculator"],
  "final-grade-calculator": ["weighted-grade-calculator", "test-grade-calculator", "gpa-calculator"],
  "weighted-grade-calculator": ["final-grade-calculator", "test-grade-calculator", "gpa-calculator"],
  "test-grade-calculator": ["weighted-grade-calculator", "final-grade-calculator", "gpa-calculator"],
  "gpa-calculator": ["weighted-grade-calculator", "final-grade-calculator", "test-grade-calculator"],
  "prime-factor-calculator": ["lcm-calculator", "gcf-calculator", "factors-calculator"],
  "slope-calculator": ["distance-calculator", "midpoint-calculator", "equation-of-line"],
  "area-of-circle": ["area-of-rectangle", "area-of-triangle", "circumference-calculator"],
  "area-of-rectangle": ["area-of-square", "area-of-triangle", "area-of-trapezoid"],
  "area-of-triangle": ["area-of-rectangle", "area-of-trapezoid", "herons-formula-calculator"],
  "area-of-trapezoid": ["area-of-rectangle", "area-of-triangle", "area-of-parallelogram"],
  "volume-of-sphere": ["volume-of-cylinder", "volume-of-cone", "surface-area-of-sphere"],
  "volume-of-cylinder": ["volume-of-cone", "volume-of-sphere", "surface-area-of-cylinder"],
  "volume-of-cone": ["volume-of-cylinder", "volume-of-sphere", "volume-of-pyramid"],
  "volume-of-cube": ["volume-of-rectangular-prism", "surface-area-of-cube", "volume-of-sphere"],
  "volume-of-rectangular-prism": ["volume-of-cube", "volume-of-cylinder", "surface-area-of-rectangular-prism"],
  "volume-of-pyramid": ["volume-of-cone", "volume-of-rectangular-prism", "volume-of-cube"],
  "number-base-converter": [
    "binary-to-decimal",
    "decimal-to-binary",
    "hex-to-decimal",
    "decimal-to-hex",
    "octal-to-decimal",
    "decimal-to-octal",
  ],
  "binary-to-decimal": ["decimal-to-binary", "binary-to-hex", "number-base-converter"],
  "decimal-to-binary": ["binary-to-decimal", "binary-to-hex", "number-base-converter"],
  "binary-to-hex": ["hex-to-binary", "binary-to-decimal", "decimal-to-hex"],
  "hex-to-binary": ["binary-to-hex", "hex-to-decimal", "binary-to-decimal"],
  "decimal-to-hex": ["hex-to-decimal", "binary-to-hex", "number-base-converter"],
  "hex-to-decimal": ["decimal-to-hex", "hex-to-binary", "number-base-converter"],
  "decimal-to-octal": ["octal-to-decimal", "number-base-converter", "binary-to-decimal"],
  "octal-to-decimal": ["decimal-to-octal", "number-base-converter", "binary-to-decimal"],
  "text-to-binary": ["binary-to-text", "ascii-converter", "hex-to-text"],
  "binary-to-text": ["text-to-binary", "ascii-converter", "hex-to-text"],
  "time-card-calculator": ["hours-calculator", "work-hours-calculator", "overtime-calculator"],
  "military-time-converter": ["time-calculator", "time-zone-converter", "time-card-calculator"],
  "scientific-calculator": ["graphing-calculator", "percentage-calculator", "fraction-calculator"],
  "fancy-text-generator": ["fancy-text-bold", "fancy-text-italic", "fancy-text-script", "fancy-text-bubble"],
  "fancy-text-bold": ["fancy-text-generator", "fancy-text-italic", "fancy-text-small-caps"],
  "fancy-text-italic": ["fancy-text-generator", "fancy-text-bold", "fancy-text-script"],
  "fancy-text-script": ["fancy-text-generator", "fancy-text-italic", "fancy-text-small-caps"],
  "fancy-text-small-caps": ["fancy-text-bold", "fancy-text-generator", "fancy-text-monospace"],
  "fancy-text-upside-down": ["fancy-text-generator", "fancy-text-bubble", "fancy-text-fullwidth"],
  "fancy-text-bubble": ["fancy-text-generator", "fancy-text-bold", "name-generator-gamer-tag"],
  "fancy-text-monospace": ["fancy-text-generator", "fancy-text-small-caps", "json-formatter"],
  "fancy-text-fullwidth": ["fancy-text-generator", "fancy-text-upside-down", "fancy-text-bold"],
  "word-unscrambler": ["typing-speed-test", "name-generator-gamer-tag", "fancy-text-generator"],
  "typing-speed-test": ["typing-speed-test-numbers", "word-unscrambler", "text-to-speech"],
  "typing-speed-test-numbers": ["typing-speed-test", "paycheck-calculator", "salary-hourly-converter"],
  "name-generator-band": ["name-generator-podcast", "name-generator-gamer-tag", "fancy-text-generator"],
  "name-generator-podcast": ["name-generator-band", "name-generator-business", "text-to-speech"],
  "name-generator-dnd": ["name-generator-clan", "name-generator-pet", "name-picker"],
  "name-generator-clan": ["name-generator-gamer-tag", "name-generator-dnd", "name-picker"],
  "name-generator-gamer-tag": ["name-generator-clan", "fancy-text-bubble", "typing-speed-test"],
  "name-generator-business": ["name-generator-band", "discount-markup-calculator", "invoice-generator"],
  "name-generator-baby": ["name-generator-pet", "due-date-calculator", "days-between-dates"],
  "name-generator-pet": ["name-generator-baby", "name-picker", "name-generator-dnd"],
  "text-to-speech": ["typing-speed-test", "word-unscrambler", "json-formatter"],
  "height-comparison": ["bmi-calculator", "tdee-calculator", "name-generator-gamer-tag"],
  "yaml-to-json": ["csv-to-json", "xml-to-json", "json-formatter"],
  "csv-to-json": ["yaml-to-json", "xml-to-json", "json-formatter"],
  "xml-to-json": ["yaml-to-json", "csv-to-json", "json-formatter"],
  "jwt-decoder": ["base64-encoder", "url-encoder", "json-formatter"],
  "url-encoder": ["base64-encoder", "jwt-decoder", "html-minifier"],
  "html-minifier": ["css-minifier", "js-minifier", "url-encoder"],
  "css-minifier": ["html-minifier", "js-minifier", "gradient-generator"],
  "js-minifier": ["html-minifier", "css-minifier", "json-formatter"],
  "webp-to-jpg": ["jpg-to-webp", "webp-to-png", "image-converter", "jpg-to-png"],
  "jpg-to-webp": ["webp-to-jpg", "png-to-webp", "image-converter", "jpg-to-png"],
  "avif-to-jpg": ["avif-to-png", "heic-to-jpg", "webp-to-jpg", "image-converter"],
  "avif-to-png": ["avif-to-jpg", "png-to-jpg", "image-converter", "svg-to-png"],
  "svg-to-png": ["png-to-ico", "favicon-generator", "image-converter", "avif-to-png"],
  "png-to-ico": ["favicon-generator", "svg-to-png", "png-to-jpg", "image-converter"],
  "tiff-to-jpg": ["heic-to-jpg", "webp-to-jpg", "image-converter", "jpg-to-png"],
  "heic-to-jpg": ["heic-to-png", "tiff-to-jpg", "jpg-to-png", "image-converter"],
  "heic-to-png": ["heic-to-jpg", "png-to-jpg", "image-converter", "avif-to-png"],
  "color-palette-generator": ["gradient-generator", "contrast-checker", "color-converter"],
  "contrast-checker": ["color-palette-generator", "color-converter", "gradient-generator"],
  "gradient-generator": ["color-palette-generator", "contrast-checker", "css-minifier"],
  "invoice-generator": ["quote-generator", "receipt-generator", "discount-markup-calculator"],
  "receipt-generator": ["invoice-generator", "quote-generator", "paycheck-calculator"],
  "quote-generator": ["invoice-generator", "receipt-generator", "discount-markup-calculator"],
  "signature-generator": ["email-signature-generator", "pdf-tools", "invoice-generator"],
  "email-signature-generator": ["signature-generator", "invoice-generator", "quote-generator"],
  "meme-generator": ["image-converter", "png-to-jpg", "fancy-text-generator"],
  "printable-calendar": ["printable-calendar-2026", "printable-calendar-2027", "days-between-dates"],
  "printable-calendar-2026": ["printable-calendar-2027", "printable-calendar", "days-between-dates"],
  "printable-calendar-2027": ["printable-calendar-2026", "printable-calendar-january-2027", "days-between-dates"],
  "printable-calendar-january-2027": ["printable-calendar-february-2027", "printable-calendar-2027", "printable-calendar"],
  "printable-calendar-february-2027": ["printable-calendar-march-2027", "printable-calendar-january-2027", "printable-calendar-2027"],
  "printable-calendar-march-2027": ["printable-calendar-february-2027", "printable-calendar-2027", "printable-calendar"],
  "image-to-text": ["pdf-tools", "image-converter", "text-to-speech"],
  "tdee-calculator": ["bmr-calculator", "macro-calculator", "bmi-calculator"],
  "bmr-calculator": ["tdee-calculator", "macro-calculator", "bmi-calculator"],
  "macro-calculator": ["tdee-calculator", "bmr-calculator", "bmi-calculator"],
  "due-date-calculator": ["days-between-dates", "name-generator-baby", "tdee-calculator"],
  "concrete-calculator": ["square-footage-calculator", "deck-calculator", "fence-calculator"],
  "square-footage-calculator": ["paint-calculator", "tile-calculator", "concrete-calculator"],
  "roof-pitch-calculator": ["square-footage-calculator", "deck-calculator", "fence-calculator"],
  "deck-calculator": ["square-footage-calculator", "concrete-calculator", "fence-calculator"],
  "mulch-calculator": ["square-footage-calculator", "fence-calculator", "paint-calculator"],
  "paint-calculator": ["square-footage-calculator", "tile-calculator", "mulch-calculator"],
  "tile-calculator": ["square-footage-calculator", "paint-calculator", "concrete-calculator"],
  "fence-calculator": ["deck-calculator", "concrete-calculator", "square-footage-calculator"],
  "paycheck-calculator": ["salary-hourly-converter", "income-tax-estimator", "macro-calculator"],
  "etsy-fee-calculator": ["ebay-fee-calculator", "paypal-fee-calculator", "discount-markup-calculator"],
  "amazon-fba-fee-calculator": ["ebay-fee-calculator", "etsy-fee-calculator", "discount-markup-calculator"],
  "ebay-fee-calculator": ["etsy-fee-calculator", "amazon-fba-fee-calculator", "paypal-fee-calculator"],
  "paypal-fee-calculator": ["etsy-fee-calculator", "invoice-generator", "paycheck-calculator"],
  "video-to-mp3": ["mp4-to-mp3", "audio-cutter", "video-compressor"],
  "mp4-to-mp3": ["video-to-mp3", "audio-cutter", "video-compressor"],
  "video-compressor": ["mp4-to-mp3", "video-to-mp3", "image-compressor"],
  "audio-cutter": ["mp4-to-mp3", "video-to-mp3", "text-to-speech"],
  "device-test-mic": ["device-test-webcam", "device-test-pack", "text-to-speech"],
  "device-test-webcam": ["device-test-mic", "device-test-pack", "device-test-dead-pixel"],
  "device-test-keyboard": ["device-test-cps", "device-test-pack", "typing-speed-test"],
  "device-test-cps": ["device-test-keyboard", "device-test-pack", "typing-speed-test"],
  "device-test-dead-pixel": ["device-test-webcam", "device-test-pack", "contrast-checker"],
  "device-test-pack": ["device-test-mic", "device-test-webcam", "device-test-keyboard", "device-test-cps", "device-test-dead-pixel"],
  "roi-calculator": [
    "budget-calculator",
    "buying-power-calculator",
    "sales-tax-calculator",
    "compound-interest-calculator",
    "break-even-calculator",
    "percentage-calculator",
  ],
  "down-payment-calculator": [
    "buying-power-calculator",
    "mortgage-calculator",
    "loan-calculator",
    "amortization-schedule",
    "refinance-calculator",
    "budget-calculator",
  ],
  "code-comparison": [
    "text-diff",
    "json-formatter",
    "json-generator",
    "regex-tester",
    "markdown-editor",
    "hash-generator",
  ],
  "png-to-webp": [
    "image-compressor",
    "image-cropper",
    "image-converter",
    "png-to-jpg",
    "webp-to-png",
    "image-resizer",
  ],
  "aspect-ratio-finder": [
    "image-cropper",
    "image-resizer",
    "image-compressor",
    "image-converter",
    "favicon-generator",
    "png-to-webp",
  ],
  "buying-power-calculator": [
    "inflation-calculator",
    "roi-calculator",
    "budget-calculator",
    "down-payment-calculator",
    "salary-hourly-converter",
    "currency-converter",
  ],
  "budget-calculator": [
    "roi-calculator",
    "emergency-fund-calculator",
    "sales-tax-calculator",
    "tip-calculator",
    "salary-hourly-converter",
    "net-worth-calculator",
  ],
  "sales-tax-calculator": [
    "budget-calculator",
    "tip-calculator",
    "discount-markup-calculator",
    "percentage-calculator",
    "roi-calculator",
    "income-tax-estimator",
  ],
  "random-number-generator": [
    "name-picker",
    "list-shuffler",
    "team-splitter",
    "dice-roller",
    "coin-flip",
    "yes-no-picker",
  ],
  "team-splitter": [
    "name-picker",
    "list-shuffler",
    "random-number-generator",
    "dice-roller",
    "coin-flip",
    "yes-no-picker",
  ],
  "emergency-fund-calculator": [
    "budget-calculator",
    "net-worth-calculator",
    "retirement-calculator",
    "debt-payoff-calculator",
    "salary-hourly-converter",
    "compound-interest-calculator",
  ],
  "image-compressor": [
    "png-to-webp",
    "image-resizer",
    "image-cropper",
    "image-converter",
    "jpg-to-png",
    "png-to-jpg",
  ],
  "image-cropper": [
    "aspect-ratio-finder",
    "image-resizer",
    "image-compressor",
    "png-to-webp",
    "background-remover",
    "favicon-generator",
  ],
  "mortgage-calculator": [
    "down-payment-calculator",
    "amortization-schedule",
    "refinance-calculator",
    "loan-calculator",
    "buying-power-calculator",
    "budget-calculator",
  ],
  "json-generator": [
    "json-formatter",
    "code-comparison",
    "regex-tester",
    "uuid-generator",
    "base64-encoder",
    "hash-generator",
  ],
  "text-diff": [
    "code-comparison",
    "word-counter",
    "case-converter",
    "remove-duplicates",
    "markdown-editor",
    "json-formatter",
  ],
};
