/** Common 5-letter words used as Wordle answers and valid guesses. */
export const WORDLE_WORDS = [
  "about", "above", "abuse", "actor", "acute", "admit", "adopt", "adult", "after", "again",
  "agent", "agree", "ahead", "alarm", "album", "alert", "alike", "alive", "allow", "alone",
  "along", "alter", "among", "anger", "angle", "angry", "apart", "apple", "apply", "arena",
  "argue", "arise", "array", "aside", "asset", "audio", "audit", "avoid", "award", "aware",
  "badly", "baker", "bases", "basic", "beach", "began", "begin", "being", "below", "bench",
  "billy", "birth", "black", "blame", "blind", "block", "blood", "board", "boost", "booth",
  "bound", "brain", "brand", "bread", "break", "breed", "brief", "bring", "broad", "broke",
  "brown", "build", "built", "buyer", "cable", "calif", "carry", "catch", "cause", "chain",
  "chair", "chart", "chase", "cheap", "check", "chest", "chief", "child", "china", "chose",
  "civil", "claim", "class", "clean", "clear", "click", "clock", "close", "coach", "coast",
  "could", "count", "court", "cover", "craft", "crash", "cream", "crime", "cross", "crowd",
  "crown", "curve", "cycle", "daily", "dance", "dated", "dealt", "death", "debut", "delay",
  "depth", "doing", "doubt", "dozen", "draft", "drama", "drawn", "dream", "dress", "drill",
  "drink", "drive", "drove", "dying", "eager", "early", "earth", "eight", "elite", "empty",
  "enemy", "enjoy", "enter", "entry", "equal", "error", "event", "every", "exact", "exist",
  "extra", "faith", "false", "fault", "fiber", "field", "fifth", "fifty", "fight", "final",
  "first", "fixed", "flash", "fleet", "floor", "fluid", "focus", "force", "forth", "forty",
  "forum", "found", "frame", "frank", "fraud", "fresh", "front", "fruit", "fully", "funny",
  "giant", "given", "glass", "globe", "going", "grace", "grade", "grand", "grant", "grass",
  "great", "green", "gross", "group", "grown", "guard", "guess", "guest", "guide", "happy",
  "harry", "heart", "heavy", "hence", "henry", "horse", "hotel", "house", "human", "ideal",
  "image", "index", "inner", "input", "issue", "japan", "jimmy", "joint", "jones", "judge",
  "known", "label", "large", "laser", "later", "laugh", "layer", "learn", "lease", "least",
  "leave", "legal", "level", "lewis", "light", "limit", "links", "lives", "local", "logic",
  "loose", "lower", "lucky", "lunch", "lying", "magic", "major", "maker", "march", "maria",
  "match", "maybe", "mayor", "meant", "media", "metal", "might", "minor", "minus", "mixed",
  "model", "money", "month", "moral", "motor", "mount", "mouse", "mouth", "movie", "music",
  "needs", "never", "newly", "night", "noise", "north", "noted", "novel", "nurse", "occur",
  "ocean", "offer", "often", "order", "other", "ought", "paint", "panel", "paper", "party",
  "peace", "peter", "phase", "phone", "photo", "piece", "pilot", "pitch", "place", "plain",
  "plane", "plant", "plate", "point", "pound", "power", "press", "price", "pride", "prime",
  "print", "prior", "prize", "proof", "proud", "prove", "queen", "quick", "quiet", "quite",
  "radio", "raise", "range", "rapid", "ratio", "reach", "ready", "refer", "right", "rival",
  "river", "robin", "roger", "roman", "rough", "round", "route", "royal", "rural", "scale",
  "scene", "scope", "score", "sense", "serve", "seven", "shall", "shape", "share", "sharp",
  "sheet", "shelf", "shell", "shift", "shine", "shirt", "shock", "shoot", "short", "shown",
  "sight", "since", "sixth", "sixty", "sized", "skill", "sleep", "slide", "small", "smart",
  "smile", "smith", "smoke", "solid", "solve", "sorry", "sound", "south", "space", "spare",
  "speak", "speed", "spend", "spent", "split", "spoke", "sport", "staff", "stage", "stake",
  "stand", "start", "state", "steam", "steel", "stick", "still", "stock", "stone", "stood",
  "store", "storm", "story", "strip", "stuck", "study", "stuff", "style", "sugar", "suite",
  "super", "sweet", "table", "taken", "taste", "taxes", "teach", "teeth", "terry", "texas",
  "thank", "theft", "their", "theme", "there", "these", "thick", "thing", "think", "third",
  "those", "three", "threw", "throw", "tight", "times", "tired", "title", "today", "topic",
  "total", "touch", "tough", "tower", "track", "trade", "train", "treat", "trend", "trial",
  "tried", "tries", "truck", "truly", "trust", "truth", "twice", "under", "undue", "union",
  "unity", "until", "upper", "upset", "urban", "usage", "usual", "valid", "value", "video",
  "virus", "visit", "vital", "vocal", "voice", "waste", "watch", "water", "wheel", "where",
  "which", "while", "white", "whole", "whose", "woman", "women", "world", "worry", "worse",
  "worst", "worth", "would", "wound", "write", "wrong", "wrote", "yield", "young", "youth",
  "abide", "abort", "acorn", "adept", "adore", "agile", "aisle", "algae", "aloud", "amber",
  "ample", "angel", "ankle", "apron", "arrow", "ashes", "atlas", "attic", "aunts", "bacon",
  "badge", "bagel", "baton", "beads", "beans", "bears", "beast", "beets", "belly", "berry",
  "bible", "bikes", "bingo", "birds", "blade", "blaze", "bleak", "blend", "bliss", "blunt",
  "blush", "boats", "bones", "bonus", "books", "boots", "bored", "brace", "brake", "brass",
  "brave", "bribe", "brick", "bride", "brisk", "broom", "brush", "buddy", "buggy", "bulbs",
  "bully", "bunch", "bunny", "burns", "burst", "buses", "cabin", "camel", "candy", "canoe",
  "cards", "cargo", "carol", "carve", "caves", "cedar", "cello", "chalk", "charm", "chess",
  "chili", "chill", "chips", "chops", "chord", "chunk", "cider", "cigar", "cinch", "civic",
  "clamp", "clang", "clasp", "claws", "cling", "clips", "cloak", "clone", "cloud", "clown",
  "clues", "clump", "cocoa", "colon", "comet", "comic", "comma", "cones", "coral", "cords",
  "corny", "couch", "cough", "crabs", "crack", "crane", "crank", "crate", "crave", "crawl",
  "craze", "crazy", "creak", "creek", "crept", "crest", "cried", "cries", "crisp", "crook",
  "crops", "crude", "cruel", "crush", "crust", "crypt", "cubic", "cumin", "curly", "curry",
  "curse", "daddy", "dairy", "daisy", "dared", "dates", "deals", "debug", "decoy", "deeds",
  "delta", "dense", "depot", "diary", "dicey", "diner", "dingo", "dirty", "disco", "ditch",
  "diver", "dizzy", "dodge", "donor", "donut", "doors", "doses", "dough", "drain", "drank",
  "drape", "dread", "dried", "drift", "drone", "drops", "drown", "drugs", "drums", "drunk",
  "dryer", "ducks", "duets", "dunes", "dusty", "dwarf", "dwell", "eagle", "easel", "eaten",
  "ebony", "edged", "eerie", "egret", "eject", "elbow", "elder", "elect", "elude", "email",
  "embed", "ember", "emote", "enact", "ended", "envoy", "epoch", "epoxy", "equip", "erase",
  "erect", "erode", "erupt", "essay", "ether", "ethic", "evade", "evict", "evoke", "exalt",
  "excel", "exert", "exile", "expel", "extol", "exult", "fable", "facet", "faded", "fails",
  "faint", "fairy", "fancy", "fangs", "farce", "farms", "fatal", "fatty", "fauna", "favor",
  "feast", "fecal", "feeds", "feels", "feign", "fella", "felon", "femme", "femur", "fence",
  "feral", "ferry", "fetal", "fetch", "fetus", "fever", "fewer", "fibre", "ficus", "fiend",
  "fiery", "filer", "filet", "fills", "films", "filth", "finch", "finds", "fined", "finer",
  "fishy", "fixes", "fjord", "flack", "flags", "flail", "flair", "flake", "flaky", "flame",
  "flank", "flare", "flask", "flats", "flaws", "fleas", "flesh", "flick", "flier", "fling",
  "flint", "flips", "flirt", "float", "flock", "flood", "flora", "floss", "flour", "flown",
  "flows", "fluke", "flume", "flung", "flunk", "flush", "flute", "foamy", "focal", "foggy",
  "foils", "folds", "folio", "folks", "fonts", "foods", "fools", "foray", "forge", "forgo",
  "forks", "forms", "forte",
  "slate", "stare", "stale", "adieu", "soare", "roate", "orate", "irate",
  "trait", "tramp", "trash", "trawl", "tread", "triad", "trice", "trier",
  "lance", "lathe", "leant", "leapt", "ledge", "snare", "snarl", "sneak",
  "snoop", "snore", "snort", "snout", "snowy"
] as const;

export const WORDLE_WORD_SET = new Set<string>(WORDLE_WORDS);

export function pickRandomWordleWord(): string {
  return WORDLE_WORDS[Math.floor(Math.random() * WORDLE_WORDS.length)];
}
